version : 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          -GO111MODULE: "ON"
    working_directory: ~/go/src/github.com/restaurant
    steps:
      - checkout
      - run: go mod verify
      - run: go test ./pkg/database
  deploy:
    machine: true
    steps:
      - checkout
        #docker build .
        #docker push registry.heroku.com/guarded-sierra-83575
        #git push https://heroku:a8e29700-1981-4a5c-b60f-71e0f74b70c2@git.heroku.com/guarded-sierra-83575.git master
      - name: Deploy Master to Heroku
      - run: docker login --username=sourav@hotcocoasoftware.com --password=a8e29700-1981-4a5c-b60f-71e0f74b70c2 registry.heroku.com
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: heroku container:push web --app guarded-sierra-83575
      - run: heroku container:release web --app guarded-sierra-83575

  printer:
        machine: true
        steps:
          - run: echo "Running from Printer"
workflows:
  version: 2
  build_and_printer_deploy:
    jobs:
      - build
      - printer
      - deploy:
          requires:
           - build
          filters:
            branches:
              only: master