version : 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          -GO111MODULE: "ON"
    working_directory: ~/go/src/github.com/restaurant
    steps:
      - checkout
      - run: go mod verify
      - run: go test ./pkg/database
  deploy:
    machine: true
    steps:
      - checkout
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: docker login --username=sourav@hotcocoasoftware.com --password=f897b601-bde5-48ac-bed9-23c38dbcf1eb registry.heroku.com
      - run: heroku container:push web --app guarded-sierra-83575
      - run: heroku container:release web --app guarded-sierra-83575

  printer:
        machine: true
        steps:
          - run: echo "Running from Printer"
workflows:
  version: 2
  build_and_printer_deploy:
    jobs:
      - build
      - printer
      - deploy:
          requires:
           - build